# Change these first
owner: cliffordwhansen
repo: upptime

secrets:
  - NOTIFICATION_DISCORD
  - NOTIFICATION_DISCORD_WEBHOOK_URL

sites:
  - name: Requests
    url: https://requests.nighthawk.co.za/login
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/seerr.svg
  - name: Plex
    url: https://plex.nighthawk.co.za
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/plex.svg
    expectedStatusCodes:
      - 401
  - name: Jellyfin
    url: https://jellyfin.nighthawk.co.za/web/
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/jellyfin.svg
  - name: Minecraft
    url: https://minecraft.nighthawk.co.za
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/minecraft.svg

  # - name: Requests IPv6
  #   url: https://requests.nighthawk.co.za/login
  #   ipv6: true
  # - name: Plex IPv6
  #   url: https://plex.nighthawk.co.za
  #   expectedStatusCodes:
  #     - 401
  #   ipv6: true
  # - name: Jellyfin IPv6
  #   url: https://jellyfin.nighthawk.co.za/web/
  #   ipv6: true
  # - name: Minecraft IPv6
  #   url: https://minecraft.nighthawk.co.za
  #   ipv6: true

assignees:
  - cliffordwhansen

status-website:
  cname: status.nighthawk.co.za
  name: NiGhTHawK Status Page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
